print("Calculating area of a room")
length = float(input("What is the length of this room in meters?"))
width = float(input("What is the width of this room in meters?"))
Area = (length * width)
print("The area of this room is:" , Area , "meters squared")
